// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QFd1aHqGQ6cB7oDXAoI9S1D8cUGkDO4',
    appId: '1:304183469581:web:52245045c08e3207919744',
    messagingSenderId: '304183469581',
    projectId: 'cinespace-5a869',
    authDomain: 'cinespace-5a869.firebaseapp.com',
    storageBucket: 'cinespace-5a869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg4SdAKVcZ0ra-0RflXWG9r270n3og-N0',
    appId: '1:304183469581:android:1ab81e58ae5048d3919744',
    messagingSenderId: '304183469581',
    projectId: 'cinespace-5a869',
    storageBucket: 'cinespace-5a869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDZz-9m-HpC3NM2vKxN2YWoKwo7b9moo',
    appId: '1:304183469581:ios:5c36bbb0d2455cd4919744',
    messagingSenderId: '304183469581',
    projectId: 'cinespace-5a869',
    storageBucket: 'cinespace-5a869.firebasestorage.app',
    iosBundleId: 'com.sagaton.cinespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2QFd1aHqGQ6cB7oDXAoI9S1D8cUGkDO4',
    appId: '1:304183469581:web:3d0127c0da816d67919744',
    messagingSenderId: '304183469581',
    projectId: 'cinespace-5a869',
    authDomain: 'cinespace-5a869.firebaseapp.com',
    storageBucket: 'cinespace-5a869.firebasestorage.app',
  );
}
